FROM php:fpm
RUN apt-get update && apt-get install -y gnupg --no-install-recommends \ 
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        librabbitmq-dev \
    && docker-php-ext-install \
        pdo_mysql \
        zip \
    && pecl install amqp \
    && docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY newsapp/ /var/www/project
COPY ./build/cron/script /var/www/scripts/
WORKDIR /var/www/project/
CMD composer require --dev dbrekelmans/bdi && vendor/bin/bdi detect drivers; bin/console doctrine:migrations:migrate ;
ENTRYPOINT ["bash", "/var/www/scripts/message_script.sh"]